/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as ProductsHandleImport } from './routes/products.$handle'
import { Route as AuthedOrdersImport } from './routes/_authed/orders'
import { Route as CheckoutCartIdInformationImport } from './routes/checkout.$cartId.information'
import { Route as AuthedOrdersOrderIdImport } from './routes/_authed/orders.$orderId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsHandleRoute = ProductsHandleImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRoute,
} as any)

const AuthedOrdersRoute = AuthedOrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthedRoute,
} as any)

const CheckoutCartIdInformationRoute = CheckoutCartIdInformationImport.update({
  id: '/checkout/$cartId/information',
  path: '/checkout/$cartId/information',
  getParentRoute: () => rootRoute,
} as any)

const AuthedOrdersOrderIdRoute = AuthedOrdersOrderIdImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AuthedOrdersRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_authed/orders': {
      id: '/_authed/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthedOrdersImport
      parentRoute: typeof AuthedImport
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleImport
      parentRoute: typeof rootRoute
    }
    '/_authed/orders/$orderId': {
      id: '/_authed/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthedOrdersOrderIdImport
      parentRoute: typeof AuthedOrdersImport
    }
    '/checkout/$cartId/information': {
      id: '/checkout/$cartId/information'
      path: '/checkout/$cartId/information'
      fullPath: '/checkout/$cartId/information'
      preLoaderRoute: typeof CheckoutCartIdInformationImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthedOrdersRouteChildren {
  AuthedOrdersOrderIdRoute: typeof AuthedOrdersOrderIdRoute
}

const AuthedOrdersRouteChildren: AuthedOrdersRouteChildren = {
  AuthedOrdersOrderIdRoute: AuthedOrdersOrderIdRoute,
}

const AuthedOrdersRouteWithChildren = AuthedOrdersRoute._addFileChildren(
  AuthedOrdersRouteChildren,
)

interface AuthedRouteChildren {
  AuthedOrdersRoute: typeof AuthedOrdersRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOrdersRoute: AuthedOrdersRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/orders': typeof AuthedOrdersRouteWithChildren
  '/products/$handle': typeof ProductsHandleRoute
  '/orders/$orderId': typeof AuthedOrdersOrderIdRoute
  '/checkout/$cartId/information': typeof CheckoutCartIdInformationRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/orders': typeof AuthedOrdersRouteWithChildren
  '/products/$handle': typeof ProductsHandleRoute
  '/orders/$orderId': typeof AuthedOrdersOrderIdRoute
  '/checkout/$cartId/information': typeof CheckoutCartIdInformationRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/orders': typeof AuthedOrdersRouteWithChildren
  '/products/$handle': typeof ProductsHandleRoute
  '/_authed/orders/$orderId': typeof AuthedOrdersOrderIdRoute
  '/checkout/$cartId/information': typeof CheckoutCartIdInformationRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/logout'
    | '/signup'
    | '/orders'
    | '/products/$handle'
    | '/orders/$orderId'
    | '/checkout/$cartId/information'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/logout'
    | '/signup'
    | '/orders'
    | '/products/$handle'
    | '/orders/$orderId'
    | '/checkout/$cartId/information'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/orders'
    | '/products/$handle'
    | '/_authed/orders/$orderId'
    | '/checkout/$cartId/information'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
  CheckoutCartIdInformationRoute: typeof CheckoutCartIdInformationRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  ProductsHandleRoute: ProductsHandleRoute,
  CheckoutCartIdInformationRoute: CheckoutCartIdInformationRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/login",
        "/logout",
        "/signup",
        "/products/$handle",
        "/checkout/$cartId/information"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/orders"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_authed/orders": {
      "filePath": "_authed/orders.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/orders/$orderId"
      ]
    },
    "/products/$handle": {
      "filePath": "products.$handle.tsx"
    },
    "/_authed/orders/$orderId": {
      "filePath": "_authed/orders.$orderId.tsx",
      "parent": "/_authed/orders"
    },
    "/checkout/$cartId/information": {
      "filePath": "checkout.$cartId.information.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
